LIBPATH := -L/usr/local/lib/

LIBS := -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_objdetect -lopencv_imgcodecs

CC := g++

facedector:main.cpp
	g++ -o facedector main.cpp $(LIBPATH) $(LIBS)

